name: Škoda Enyaq
version: 2026.09.198
slug: ha-addon-skoda-enyaq
description: "Reads the current battery's state of charge (SoC) from the vehicle."
arch:
- aarch64
init: false
watchdog: http://[HOST]:[PORT:5000]/livez
services:
 - mqtt:need
image: ghcr.io/martinmgraf/ha-addon-skoda-enyaq

options:
  skoda_api_key:
  skoda_vehicle_vin:
  skoda_polling_interval_minutes:
schema:
  skoda_api_key: password
  skoda_vehicle_vin: str(17,17)
  skoda_polling_interval_minutes: int(5,)