name: Škoda Enyaq
version: 2025.08.101
slug: ha-addon-skoda-enyaq
description: "Reads the current battery's state of charge (SoC) from the vehicle."
arch:
- aarch64
init: false
watchdog: http://[HOST]:[PORT:5000]/livez
homeassistant_api: true
hassio_api: true
hassio_role: admin
image: ghcr.io/martinmgraf/ha-addon-skoda-enyaq